/*GUI for add a new series
Ross van der Heyde
17 Feb 2017
 */
package gui;

import library.Series;
import util.PopUpMessages;

import java.awt.event.KeyEvent;
import java.util.logging.Logger;

/**
 *
 * @author Ross
 */
public class AddSeriesGUI extends javax.swing.JFrame {
    private static Logger logger = Logger.getLogger(AddSeriesGUI.class.getName());

    private javax.swing.JButton butAdd;
    private javax.swing.JButton butCancel;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labNumBooks;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNumBooks;

    /**
     * Creates new form AddSeriesGUI
     */
    public AddSeriesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        labName = new javax.swing.JLabel();
        labNumBooks = new javax.swing.JLabel();
        butAdd = new javax.swing.JButton();
        butCancel = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        tfNumBooks = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add a new series");

        labName.setText("Name:");

        labNumBooks.setText("Number of books:");

        butAdd.setText("Add");
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });
        butAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butAddKeyReleased(evt);
            }
        });

        butCancel.setText("Cancel");
        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });
        butCancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butCancelKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labNumBooks)
                            .addComponent(labName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfName)
                            .addComponent(tfNumBooks)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(236, Short.MAX_VALUE)
                        .addComponent(butAdd)
                        .addGap(26, 26, 26)
                        .addComponent(butCancel)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labName)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNumBooks)
                    .addComponent(tfNumBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAdd)
                    .addComponent(butCancel))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>

    /**
     * Runs when the cancel button is clicked. Disposes of this window
     *
     * @param evt The button click event
     */
    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();

    }

    /**
     * Runs when the add button is clicked. Creates new series, then add to
     * database
     *
     * @param evt button click event
     */
    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {
        Series series = new Series();

        series.setName(tfName.getText());
        series.setNumberOfBooks(Integer.parseInt(tfNumBooks.getText()));

        if (series.addToDatabase()) {
            PopUpMessages.infoMessageNormal(series.getName() + " successfully added to the database.");
        } else {
            PopUpMessages.errorMessageNormal("Series could not be added.");
        }

        this.dispose();
    }

    private void butAddKeyReleased(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            butAddActionPerformed(null);
        }
    }

    private void butCancelKeyReleased(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            butCancelActionPerformed(null);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSeriesGUI().setVisible(true);
            }
        });
    }
}
