/*
 GUI to add a new borrower to the database
 Ross van der Heyde
 26 January 2015
 */
package GUIs;

import library.Borrower;
import library.Driver;

/**
 *  JFrame for adding a new borrower to the database. 
 * @author ross
 */
public class AddBorrower extends javax.swing.JFrame {

    /**
     * Creates new form AddBorrower
     */
    public AddBorrower() {
        initComponents();
        pAdd.setVisible(false);
        pUpdate.setVisible(false);
        pDelete.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAdd = new javax.swing.JPanel();
        lNumber = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfNumber = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        lEmail = new javax.swing.JLabel();
        butCancel = new javax.swing.JButton();
        butAdd = new javax.swing.JButton();
        pDelete = new javax.swing.JPanel();
        lBorID = new javax.swing.JLabel();
        tfDelID = new javax.swing.JTextField();
        butCancel1 = new javax.swing.JButton();
        butDelete = new javax.swing.JButton();
        pUpdate = new javax.swing.JPanel();
        lField = new javax.swing.JLabel();
        lNewValue = new javax.swing.JLabel();
        lUpdateID = new javax.swing.JLabel();
        tfUpdateID = new javax.swing.JTextField();
        tfNewValue = new javax.swing.JTextField();
        comboUpdate = new javax.swing.JComboBox();
        butUpdate = new javax.swing.JButton();
        butCancel2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pAdd.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lNumber.setText("Contact number:");

        lName.setText("Full name:");

        lEmail.setText("E-mail address:");

        butCancel.setText("Cancel");
        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        butAdd.setText("Add");
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAddLayout = new javax.swing.GroupLayout(pAdd);
        pAdd.setLayout(pAddLayout);
        pAddLayout.setHorizontalGroup(
            pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pAddLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAddLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(butAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(butCancel))
                        .addGroup(pAddLayout.createSequentialGroup()
                            .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lNumber)
                                .addComponent(lName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfName)
                                .addComponent(tfNumber)
                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 80, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        pAddLayout.setVerticalGroup(
            pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
            .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pAddLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lName)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lNumber)
                        .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lEmail)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butAdd)
                        .addComponent(butCancel))
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        pDelete.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lBorID.setText("Borrower ID:");

        butCancel1.setText("Cancel");
        butCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancel1ActionPerformed(evt);
            }
        });

        butDelete.setText("Delete");
        butDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDeleteLayout = new javax.swing.GroupLayout(pDelete);
        pDelete.setLayout(pDeleteLayout);
        pDeleteLayout.setHorizontalGroup(
            pDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lBorID)
                .addGap(18, 18, 18)
                .addComponent(tfDelID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDeleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(butCancel1)
                .addContainerGap())
        );
        pDeleteLayout.setVerticalGroup(
            pDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDeleteLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBorID)
                    .addComponent(tfDelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butDelete)
                    .addComponent(butCancel1))
                .addContainerGap())
        );

        pUpdate.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lField.setText("Field to update:");

        lNewValue.setText("New value:");

        lUpdateID.setText("Borrower ID:");

        comboUpdate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "Contact number", "E-mail address" }));

        butUpdate.setText("Update");
        butUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateActionPerformed(evt);
            }
        });

        butCancel2.setText("Cancel");
        butCancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUpdateLayout = new javax.swing.GroupLayout(pUpdate);
        pUpdate.setLayout(pUpdateLayout);
        pUpdateLayout.setHorizontalGroup(
            pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lNewValue)
                    .addComponent(lUpdateID)
                    .addComponent(lField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNewValue)
                    .addComponent(tfUpdateID)
                    .addComponent(comboUpdate, 0, 177, Short.MAX_VALUE))
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butUpdate)
                .addGap(18, 18, 18)
                .addComponent(butCancel2)
                .addGap(9, 9, 9))
        );
        pUpdateLayout.setVerticalGroup(
            pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUpdateID)
                    .addComponent(tfUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lField)
                    .addComponent(comboUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNewValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNewValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butUpdate)
                    .addComponent(butCancel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    ActionPerformed method for add button. Gets data from GUI, creates <code>Borrower</code>
    and adds to the database.
    @param evt the button click event.
    */
    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddActionPerformed
        Borrower bor = new Borrower();//create new borrower

        //set borrower's details
        bor.setName(tfName.getText());
        bor.setNumber(tfNumber.getText());
        bor.setEMail(tfEmail.getText());

        //add to DB, inform of success/failure
        if (bor.addToDatabase()) {
            driver.infoMessageNormal("Borrower successfully added to the database.");
            this.dispose();
        } else {
            driver.infoMessageNormal("Borrower could not be added.");
        }
    }//GEN-LAST:event_butAddActionPerformed

    /**
    ActionPerformed method for cancel button. Closes the window
    @param evt the button click event.
    */
    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_butCancelActionPerformed

/**
    AP method for second cancel button
    @param evt the button click event.
    */
    private void butCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancel1ActionPerformed
        butCancelActionPerformed(null);
    }//GEN-LAST:event_butCancel1ActionPerformed

    /**
    ActionPerformed method for delete button. Deletes a borrower from the
    database
    @param evt the button click event.
    */
    private void butDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeleteActionPerformed
        int id = Integer.parseInt(tfDelID.getText());//get borrower ID

        //create new borrower
        Borrower b = new Borrower(id, driver);

        //perform deletion and inform user of success/failure
        if (b.deleteFromDatabase()) {
            driver.infoMessageNormal("Borrower succeddfully deleted.");
            this.dispose();
        } else {
            driver.infoMessageNormal("Borrower was not deleted.");
        }
    }//GEN-LAST:event_butDeleteActionPerformed

/**
    ActionPerformed method for third cancel button button.
    @param evt the button click event.
    */
    private void butCancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancel2ActionPerformed
        butCancelActionPerformed(null);
    }//GEN-LAST:event_butCancel2ActionPerformed

    /**
    ActionPerformed method for update button. Gets data from GUI, creates <code>Author</code>
    and updates it in the database
    @param evt the button click event.
    */
    private void butUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butUpdateActionPerformed

    /**
     * Set delete, add, or update panel visible depending on parameter
     *
     * @param p Integer indicating panel to be visible. 0- add, 1- update, 2-
     * delete
     */
    public void setVisiblePanel(int p) {
        switch (p) {
            case 0: {
                //set add panel visble
                pAdd.setVisible(true);

                //set size of AddBorrower JFrame to just bigger than size of visible panel
                this.setSize(pAdd.getWidth(), pAdd.getHeight() + 40);
                
                //set title of JFrame to something appropriate
                this.setTitle("Add a new borrower to the database | MyLibrary");
                
                break;
            }
            case 1: {
                //set update panel visible
                pUpdate.setVisible(true);
                
                this.setSize(pUpdate.getWidth(), pUpdate.getHeight() + 40);
                this.setTitle("Update a borrower's details | MyLibrary");
                
                break;
            }
            case 2: {
                //set delete panel visble 
                pDelete.setVisible(true);
                
                this.setSize(pDelete.getWidth(), pDelete.getHeight() + 30);
                this.setTitle("Delete a borrower from the database | MyLibrary");
                
                break;
            }
            default: {
                driver.errorMessageNormal("Invalid setVisiblePanel parameter. Must be 0, 1, or 2");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBorrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBorrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBorrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBorrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBorrower().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdd;
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butCancel1;
    private javax.swing.JButton butCancel2;
    private javax.swing.JButton butDelete;
    private javax.swing.JButton butUpdate;
    private javax.swing.JComboBox comboUpdate;
    private javax.swing.JLabel lBorID;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lField;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lNewValue;
    private javax.swing.JLabel lNumber;
    private javax.swing.JLabel lUpdateID;
    private javax.swing.JPanel pAdd;
    private javax.swing.JPanel pDelete;
    private javax.swing.JPanel pUpdate;
    private javax.swing.JTextField tfDelID;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNewValue;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JTextField tfUpdateID;
    // End of variables declaration//GEN-END:variables
    private Driver driver = new Driver();
    
}
