/*Panel for adding book.
Ross van der Heyde
26 February 2017. Got 63% for EEE2026S, Justin must've given me some free marks.
 */
package GUIs;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;

import library.*;
import library.TypeOfBook;

/**
 * A <code>JPanel</code> that provides the interface and functionality for
 * adding books to the database. This panel is added to the tabbed pane on the
 * main GUI
 *
 * @author Ross
 */
public class AddPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel.
     *
     * @param d An instance of <code>Driver</code>
     */
    public AddPanel(Driver d) {
        driver = d;
        initComponents();

        radAddDum.setVisible(false);

        comboShop.setModel(driver.getComboBoxModel(0));
        comboGenre.setModel(driver.getComboBoxModel(1));
        comboType.setModel(driver.getComboBoxModel(2));

//deweyOne and roles not necessary
        comboSeries.setModel(driver.getComboBoxModel(5));
        AutoCompletion.enable(comboSeries); //enable autocompletion
        comboSeries.setSelectedIndex(-1);

        comboAuthor.setModel(driver.getComboBoxModel(6));
        AutoCompletion.enable(comboAuthor);
        comboAuthor.setSelectedIndex(-1);

        //set models for dew2 and dew3 comboBoxes
        comboDew1ItemStateChanged(null);
        comboDew2ItemStateChanged(null);

//        butAdd.setFocusPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        radFiction = new javax.swing.JRadioButton();
        radNonFic = new javax.swing.JRadioButton();
        radAddDum = new javax.swing.JRadioButton();
        lTitle = new javax.swing.JLabel();
        lAuthor = new javax.swing.JLabel();
        lPrice = new javax.swing.JLabel();
        lPlace = new javax.swing.JLabel();
        lPublished = new javax.swing.JLabel();
        lDate = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        tfDate = new javax.swing.JTextField();
        tfPublished = new javax.swing.JTextField();
        butAddAuthors = new javax.swing.JButton();
        comboShop = new javax.swing.JComboBox();
        butAddShop = new javax.swing.JButton();
        addFictionPanel = new javax.swing.JPanel();
        lFiction = new javax.swing.JLabel();
        lGenre = new javax.swing.JLabel();
        lType = new javax.swing.JLabel();
        lSeries = new javax.swing.JLabel();
        lNumSeries = new javax.swing.JLabel();
        tfNumber = new javax.swing.JTextField();
        comboGenre = new javax.swing.JComboBox();
        comboType = new javax.swing.JComboBox();
        addGenre = new javax.swing.JButton();
        addType = new javax.swing.JButton();
        butAddSeries = new javax.swing.JButton();
        comboSeries = new javax.swing.JComboBox<>();
        addNonPanel = new javax.swing.JPanel();
        lGeneral = new javax.swing.JLabel();
        lSpec = new javax.swing.JLabel();
        lNonFiction = new javax.swing.JLabel();
        comboDew1 = new javax.swing.JComboBox<>();
        comboDew2 = new javax.swing.JComboBox();
        lThree = new javax.swing.JLabel();
        comboDew3 = new javax.swing.JComboBox();
        butClear = new javax.swing.JButton();
        butAdd = new javax.swing.JButton();
        pMessage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taMessages = new javax.swing.JTextPane();
        butClearMess = new javax.swing.JButton();
        butAddNewAuthors = new javax.swing.JButton();
        comboAuthor = new javax.swing.JComboBox<>();

        buttonGroup.add(radFiction);
        radFiction.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        radFiction.setText("Fiction");
        radFiction.setToolTipText("Select whether you are adding a fiction or non-fiction book.");

        buttonGroup.add(radNonFic);
        radNonFic.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        radNonFic.setText("Non-fiction");
        radNonFic.setToolTipText("Select whether you are adding a fiction or non-fiction book.");

        buttonGroup.add(radAddDum);
        radAddDum.setText("dumb");

        lTitle.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lTitle.setText("Title:");

        lAuthor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lAuthor.setText("Author:");

        lPrice.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lPrice.setText("Price:");

        lPlace.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lPlace.setText("Place Bought:");

        lPublished.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lPublished.setText("First published:");

        lDate.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lDate.setText("Date Bought:");

        tfTitle.setToolTipText("The title of the book.");

        tfPrice.setToolTipText("Amount paid for the book.");

        tfDate.setToolTipText("Month and year book was bought (MM/YYYY).");

        tfPublished.setToolTipText("The year the book was first published.");

        butAddAuthors.setText("Add multiple");
        butAddAuthors.setToolTipText("Add an editor, illustrator, or more than one author.");
        butAddAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddAuthorsActionPerformed(evt);
            }
        });
        butAddAuthors.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butAddAuthorsKeyReleased(evt);
            }
        });

        comboShop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboShop.setToolTipText("Select the shop where the book was bought.");

        butAddShop.setText("Add shop");
        butAddShop.setToolTipText("Add a new shop to the database.");
        butAddShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddShopActionPerformed(evt);
            }
        });
        butAddShop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butAddShopKeyReleased(evt);
            }
        });

        addFictionPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lFiction.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lFiction.setText("<html><b><u>Fiction only</u></b>");

        lGenre.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lGenre.setText("Genre:");

        lType.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lType.setText("Type of book:");

        lSeries.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lSeries.setText("Series:");

        lNumSeries.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lNumSeries.setText("Number in series:");

        tfNumber.setToolTipText("Number the book is in the series. Enter 0 if not part of a series.");

        comboGenre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboGenre.setToolTipText("The book's genre.");

        comboType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboType.setToolTipText("The type of book (novel, play, poems, etc).");

        addGenre.setText("Add new genre");
        addGenre.setToolTipText("Add a new genre to the database.");
        addGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGenreActionPerformed(evt);
            }
        });
        addGenre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addGenreKeyReleased(evt);
            }
        });

        addType.setText("Add new type");
        addType.setToolTipText("Add a new type of book.");
        addType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTypeActionPerformed(evt);
            }
        });
        addType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addTypeKeyReleased(evt);
            }
        });

        butAddSeries.setText("Add new series");
        butAddSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddSeriesActionPerformed(evt);
            }
        });
        butAddSeries.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butAddSeriesKeyReleased(evt);
            }
        });

        comboSeries.setEditable(true);
        comboSeries.setToolTipText("<html>Select the series that the book is part of<br>\nIf the series is not in the list, add it using the 'add<br>\nnew series' button.");

        javax.swing.GroupLayout addFictionPanelLayout = new javax.swing.GroupLayout(addFictionPanel);
        addFictionPanel.setLayout(addFictionPanelLayout);
        addFictionPanelLayout.setHorizontalGroup(
            addFictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFictionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addFictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lGenre)
                    .addComponent(lType)
                    .addComponent(lSeries)
                    .addGroup(addFictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lFiction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lNumSeries)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addFictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboGenre, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboSeries, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addFictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addFictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addGenre)
                        .addComponent(addType, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(butAddSeries))
                .addGap(118, 118, 118))
        );
        addFictionPanelLayout.setVerticalGroup(
            addFictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFictionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFiction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(addFictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGenre)
                    .addComponent(comboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGenre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addFictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lType)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addFictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSeries)
                    .addComponent(butAddSeries)
                    .addComponent(comboSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addFictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumSeries)
                    .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        addNonPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lGeneral.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lGeneral.setText("Dewey level 1:");

        lSpec.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lSpec.setText("Level 2:");

        lNonFiction.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lNonFiction.setText("<html><b><u>Non-fiction only</u></b>");
        lNonFiction.setToolTipText("Fill in these fields only if you are adding a non-fiction book.");

        comboDew1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Generalities, Computer Science & Information", "Philosophy & psychology", "Religion", "Social sciences", "Language", "Natural sciences & mathematics", "Technology (Applied sciences)", "The arts", "Literature & rhetoric", "Geography & history" }));
        comboDew1.setToolTipText("General topic that the book covers.");
        comboDew1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDew1ItemStateChanged(evt);
            }
        });

        comboDew2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDew2.setToolTipText("More specific topic.");
        comboDew2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDew2ItemStateChanged(evt);
            }
        });

        lThree.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lThree.setText("Level 3:");

        comboDew3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout addNonPanelLayout = new javax.swing.GroupLayout(addNonPanel);
        addNonPanel.setLayout(addNonPanelLayout);
        addNonPanelLayout.setHorizontalGroup(
            addNonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNonPanelLayout.createSequentialGroup()
                        .addComponent(lGeneral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboDew1, 0, 1, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(lNonFiction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addNonPanelLayout.createSequentialGroup()
                        .addGroup(addNonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addNonPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lThree))
                            .addComponent(lSpec, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addNonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboDew2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboDew3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(357, 357, 357))
        );
        addNonPanelLayout.setVerticalGroup(
            addNonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lNonFiction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGeneral)
                    .addComponent(comboDew1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(addNonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSpec)
                    .addComponent(comboDew2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lThree)
                    .addComponent(comboDew3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        butClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        butClear.setText("Clear all");
        butClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClearActionPerformed(evt);
            }
        });
        butClear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butClearKeyReleased(evt);
            }
        });

        butAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        butAdd.setText("Add");
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });
        butAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butAddKeyReleased(evt);
            }
        });

        pMessage.setBorder(javax.swing.BorderFactory.createTitledBorder("Messages"));

        taMessages.setEditable(false);
        taMessages.setToolTipText("Messages from the database appear here.");
        jScrollPane2.setViewportView(taMessages);

        javax.swing.GroupLayout pMessageLayout = new javax.swing.GroupLayout(pMessage);
        pMessage.setLayout(pMessageLayout);
        pMessageLayout.setHorizontalGroup(
            pMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        pMessageLayout.setVerticalGroup(
            pMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        butClearMess.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        butClearMess.setText("Clear messages");
        butClearMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClearMessActionPerformed(evt);
            }
        });
        butClearMess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butClearMessKeyReleased(evt);
            }
        });

        butAddNewAuthors.setText("Add new author(s)");
        butAddNewAuthors.setToolTipText("Add new authors to the database.");
        butAddNewAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddNewAuthorsActionPerformed(evt);
            }
        });
        butAddNewAuthors.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butAddNewAuthorsKeyReleased(evt);
            }
        });

        comboAuthor.setEditable(true);
        comboAuthor.setToolTipText("<html>Select the author of the book.<br>\nIf the author is not in the list,<br>\nadd the author using the 'Add<br> \nnew author(s)' button.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butAdd)
                        .addGap(18, 18, 18)
                        .addComponent(butClearMess)
                        .addGap(18, 18, 18)
                        .addComponent(butClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lPublished)
                                            .addComponent(lDate, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lPlace, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lAuthor, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfTitle)
                                            .addComponent(tfPublished)
                                            .addComponent(tfDate)
                                            .addComponent(tfPrice)
                                            .addComponent(comboShop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboAuthor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(butAddAuthors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(butAddShop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(radFiction)
                                        .addGap(29, 29, 29)
                                        .addComponent(radNonFic)
                                        .addGap(37, 37, 37)
                                        .addComponent(radAddDum)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butAddNewAuthors)
                                .addGap(200, 200, 200))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addFictionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addNonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(14, 14, 14)))
                        .addComponent(pMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radFiction)
                            .addComponent(radNonFic)
                            .addComponent(radAddDum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTitle)
                            .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lAuthor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(butAddAuthors)
                                    .addComponent(butAddNewAuthors)
                                    .addComponent(comboAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfPublished, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lPublished))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPrice)
                            .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPlace)
                            .addComponent(comboShop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butAddShop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDate)
                            .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(addFictionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addNonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butClear)
                            .addComponent(butClearMess)
                            .addComponent(butAdd))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    //open GUI for adding new authors
    private void butAddAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddAuthorsActionPerformed
        final AddMultipleAuthors ama = new AddMultipleAuthors();

        ama.setVisible(true);

        ama.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                multipleAuthors = ama.getAuthors();

                comboAuthor.setSelectedItem("Multiple...");
            }
        });
    }//GEN-LAST:event_butAddAuthorsActionPerformed

    //open GUI for for adding new shops
    private void butAddShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddShopActionPerformed
        ShopGUI sg = new ShopGUI();

        sg.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                comboShop.setModel(driver.getComboBoxModel(0));//shop
            }
        });

        sg.setVisible(true);
    }//GEN-LAST:event_butAddShopActionPerformed

    //open GUI for adding new genre
    private void addGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGenreActionPerformed
        //create new GenreGUI
        GenreGUI gg = new GenreGUI();

        gg.setVisible(true);//set gui visible

        //add windowListner. Listens for and runs when window is closed
        gg.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                comboGenre.setModel(driver.getComboBoxModel(1));//genre
            }
        });
    }//GEN-LAST:event_addGenreActionPerformed

    //open GUI for adding new type of book
    private void addTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTypeActionPerformed
        // Create new TYpeGUI
        TypeGUI tg = new TypeGUI();

        tg.setVisible(true);//set gui visible

        //add windowListner. Listens for and runs when window is closed
        tg.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                comboType.setModel(driver.getComboBoxModel(2));//type
            }
        });
    }//GEN-LAST:event_addTypeActionPerformed

    //open GUI for adding new series
    private void butAddSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddSeriesActionPerformed
        AddSeriesGUI gui = new AddSeriesGUI();
        gui.setVisible(true);

        gui.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
                //refresh comboSeries
                comboSeries.setModel(driver.getComboBoxModel(5));
            }
        });
    }//GEN-LAST:event_butAddSeriesActionPerformed

    private void comboDew1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDew1ItemStateChanged
        //set model for dewey2

        //get dewey level 1 number
        int dew1 = comboDew1.getSelectedIndex() * 100;

        DefaultComboBoxModel model = driver.getDewey2Model(dew1, (String) comboDew1.getSelectedItem());

        //set dew2's model
        comboDew2.setModel(model);
    }//GEN-LAST:event_comboDew1ItemStateChanged

    private void comboDew2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDew2ItemStateChanged
        //set model for dewey3

        //get dewey level 2 number
        int dew2 = (comboDew1.getSelectedIndex() * 100) + comboDew2.getSelectedIndex() * 10;

        comboDew3.setModel(driver.getDewey3Model(dew2, comboDew2.getSelectedItem()));
    }//GEN-LAST:event_comboDew2ItemStateChanged

    //remove text from all textfields, textAreas, select nothing in comboBoxes
    private void butClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClearActionPerformed
        //textFields
        tfTitle.setText(null);
        comboAuthor.setSelectedIndex(-1);
        tfPrice.setText(null);
        tfDate.setText(null);
        tfPublished.setText(null);
        comboSeries.setSelectedIndex(-1);
        tfNumber.setText(null);

        //select radDum
        radAddDum.setSelected(true);

        //comboBoxes
        comboShop.setSelectedIndex(0);
        comboGenre.setSelectedIndex(0);
        comboType.setSelectedIndex(0);
        comboDew1.setSelectedIndex(0);
        comboDew2.setSelectedIndex(0);
        comboDew3.setSelectedIndex(0);

        //messages
        taMessages.setText("");
    }//GEN-LAST:event_butClearActionPerformed

    //get info from textfields and add new book to database
    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddActionPerformed
        Book book = new Book();

        //get inputs and set book's variables
        book.setTitle(tfTitle.getText());                           //title

        //authors
        if (multipleAuthors == null) {
            //add one author
            String authName = comboAuthor.getSelectedItem().toString();
            Author auth = new Author(authName, new Role("Author"));

            book.addAuthor(auth);
        } else {
            //add multiple authors
            for (Author author : multipleAuthors) {
                book.addAuthor(author);
            }
        }

        book.setPrice(Double.parseDouble(tfPrice.getText()));       //price

        //month and year: split date on /
        String[] temp = tfDate.getText().split("/");
        book.setMonth(Integer.parseInt(temp[0]));                   //set month
        book.setYear(Integer.parseInt(temp[1]));                    //set year

        book.setPublished(Integer.parseInt(tfPublished.getText())); //year first published

        //set place bought
        Shop shop = new Shop(comboShop.getSelectedItem().toString());
        //shop ID set in the above constructor.
        System.out.println("library.MainGUI.butAddActionPerformed() shop: " + shop.toString());
        book.setShop(shop);

        //see if fiction or non-fiction
        if (radFiction.isSelected()) {
            //<editor-fold defaultstate="collapsed" desc="Add fiction book">
            //fiction
            Fiction fictionBook = new Fiction(book);

            try {
                //fiction specific inuts
                //set genre
                Genre gen = new Genre(comboGenre.getSelectedItem().toString());
                fictionBook.setGenre(gen);

                //set type of book
                TypeOfBook type = new TypeOfBook(comboType.getSelectedItem().toString());
                fictionBook.setType(type);

                fictionBook.setNumber(Integer.parseInt(tfNumber.getText()));       //set number in series

                //create and set series
                Series ser = new Series(comboSeries.getSelectedItem().toString());
                fictionBook.setSeries(ser);

                System.out.println("library.MainGUI.butAddActionPerformed() fictionbook.getShop: " + fictionBook.getShop());

                //add book to the database
                if (fictionBook.addToDatabase()) {
                    //added successfully

                    //inform user
                    appendToPane("\"" + fictionBook.getTitle() + "\" successfully added to the database.\n", Color.green);
                } else {
                    //some error

                    //inform user
                    appendToPane("\"" + fictionBook.getTitle() + "\" could not be added.\n", Color.red);
                }

            } catch (NumberFormatException nfe) {
                appendToPane("Please enter digits only in the first published "
                        + "and price fields. Also ensure that the date is in the correct format.\n", Color.orange);

                nfe.printStackTrace();
            }

            //</editor-fold>
        } else if (radNonFic.isSelected()) {
            //<editor-fold defaultstate="collapsed" desc="Add non-fiction book">
            //create non fiction book
            NonFiction nonFictionBook = new NonFiction(book);

            try {
                //non-fiction only inputs
                int dewey = comboDew1.getSelectedIndex() * 100
                        + comboDew2.getSelectedIndex() * 10
                        + comboDew3.getSelectedIndex();

                nonFictionBook.setDeweyNumber(dewey);//set dewey number

                //add book, inform of success (or lack thereof)
                if (nonFictionBook.addToDatabase()) {
                    appendToPane("\"" + nonFictionBook.getTitle() + "\"added successfully to the database.\n", Color.green);
                } else {
                    appendToPane("\"" + nonFictionBook.getTitle() + "\" could not be added to the database.\n", Color.red);
                }

            } catch (NumberFormatException nfe) {
                appendToPane("Please enter digits only in the first published "
                        + "and price fields. Also ensure that the date is in the correct format.\n", Color.orange);
                System.out.println("GUIs.MainGUI.butAddActionPerformed() " + nfe);
                nfe.printStackTrace();
            }

            //</editor-fold>
        } else {
            driver.infoMessageNormal("Please select whether to the book is fiction or non-fiction.");
        }
    }//GEN-LAST:event_butAddActionPerformed

    //clear text from text area
    private void butClearMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClearMessActionPerformed
        taMessages.setText("");
    }//GEN-LAST:event_butClearMessActionPerformed

    //open GUI for adding new authors(s)
    private void butAddNewAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddNewAuthorsActionPerformed
        AddNewAuthors add = new AddNewAuthors();

        add.setVisible(true);

        add.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
                //refresh combo authors

                comboAuthor.setModel(driver.getComboBoxModel(6));
            }
        });
    }//GEN-LAST:event_butAddNewAuthorsActionPerformed

    private void butAddAuthorsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butAddAuthorsKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            butAddAuthorsActionPerformed(null);
        }
    }//GEN-LAST:event_butAddAuthorsKeyReleased

    private void butAddNewAuthorsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butAddNewAuthorsKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            butAddNewAuthorsActionPerformed(null);
        }
    }//GEN-LAST:event_butAddNewAuthorsKeyReleased

    private void butAddShopKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butAddShopKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            butAddSeriesActionPerformed(null);
        }
    }//GEN-LAST:event_butAddShopKeyReleased

    private void addGenreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addGenreKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addGenreActionPerformed(null);
        }
    }//GEN-LAST:event_addGenreKeyReleased

    private void addTypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addTypeKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addTypeActionPerformed(null);
        }
    }//GEN-LAST:event_addTypeKeyReleased

    private void butAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butAddKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            butAddActionPerformed(null);
        }
    }//GEN-LAST:event_butAddKeyReleased

    private void butAddSeriesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butAddSeriesKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            butAddSeriesActionPerformed(null);
        }
    }//GEN-LAST:event_butAddSeriesKeyReleased

    private void butClearMessKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butClearMessKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            butClearMessActionPerformed(null);
        }
    }//GEN-LAST:event_butClearMessKeyReleased

    private void butClearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butClearKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            butClearActionPerformed(null);
        }
    }//GEN-LAST:event_butClearKeyReleased

    /**
     * Add text to JTextPane for messages
     *
     * @param tp JTextPane to add text tor
     * @param msg Text to be added
     * @param c Colour of text
     */
//    private void appendToPane(JTextPane tp, String msg, Color c) {
    private void appendToPane(String msg, Color c) {
        StyleContext sc = StyleContext.getDefaultStyleContext();
        AttributeSet aset = sc.addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground, c);

        aset = sc.addAttribute(aset, StyleConstants.FontFamily, "Lucida Console");
        aset = sc.addAttribute(aset, StyleConstants.Alignment, StyleConstants.ALIGN_JUSTIFIED);

        /*int len = tp.getDocument().getLength();
        tp.setCaretPosition(len);
        tp.setCharacterAttributes(aset, false);
        tp.replaceSelection(msg);*/
        int len = taMessages.getDocument().getLength();
        taMessages.setCaretPosition(len);
        taMessages.setCharacterAttributes(aset, false);
        taMessages.replaceSelection(msg);
        System.out.println("MEssage that should have beenon the textpane: " + msg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addFictionPanel;
    private javax.swing.JButton addGenre;
    private javax.swing.JPanel addNonPanel;
    private javax.swing.JButton addType;
    private javax.swing.JButton butAdd;
    private javax.swing.JButton butAddAuthors;
    private javax.swing.JButton butAddNewAuthors;
    private javax.swing.JButton butAddSeries;
    private javax.swing.JButton butAddShop;
    private javax.swing.JButton butClear;
    private javax.swing.JButton butClearMess;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<String> comboAuthor;
    private javax.swing.JComboBox<String> comboDew1;
    private javax.swing.JComboBox comboDew2;
    private javax.swing.JComboBox comboDew3;
    private javax.swing.JComboBox comboGenre;
    private javax.swing.JComboBox<String> comboSeries;
    private javax.swing.JComboBox comboShop;
    private javax.swing.JComboBox comboType;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lAuthor;
    private javax.swing.JLabel lDate;
    private javax.swing.JLabel lFiction;
    private javax.swing.JLabel lGeneral;
    private javax.swing.JLabel lGenre;
    private javax.swing.JLabel lNonFiction;
    private javax.swing.JLabel lNumSeries;
    private javax.swing.JLabel lPlace;
    private javax.swing.JLabel lPrice;
    private javax.swing.JLabel lPublished;
    private javax.swing.JLabel lSeries;
    private javax.swing.JLabel lSpec;
    private javax.swing.JLabel lThree;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lType;
    private javax.swing.JPanel pMessage;
    private javax.swing.JRadioButton radAddDum;
    private javax.swing.JRadioButton radFiction;
    private javax.swing.JRadioButton radNonFic;
    private javax.swing.JTextPane taMessages;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfPublished;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Author> multipleAuthors = null;
    final private Driver driver;

}
